### ISSUE TITLE
Commas in name result in truncation

### ISSUE THREAD

**Issue by powellad** [dasiths/NEasyAuthMiddleware#2]
Having commas in the `name` field result in the name being truncated. I assume this is due to the `Split(',')` call in the middleware. 

`{
   "typ": "name",
   "val": "User, Mock"
}`

Results in only "User" being added to the claim as the Identity.

**Comment by dasiths** [comment]
You mean here? https://github.com/dasiths/NEasyAuthMiddleware/blob/143264c1d70e9a99481176eb1ce5490724855334/NEasyAuthMiddleware/Mappers/StandardPrincipalClaimMapper.cs#L49

**Comment by dasiths** [comment]
Fixed in https://github.com/dasiths/NEasyAuthMiddleware/commit/6a8f2155ca5de95e5e5e33917ce297b004c7ed5e

This allows customisation of the behaviour via `EasyAuthOptions.ClaimTypesWithCommaSeparatedValues` setting.
