### ISSUE TITLE
user.Identity.IsAuthenticated is always false

### ISSUE THREAD

**Issue by perfectphase** [dasiths/NEasyAuthMiddleware#3]
Using this library in a .Net Core 3.1 project and user.Identity.IsAuthenticated is always false.

Had a look around and it seems that you must pass an authentication type as well as your claims into the ClaimsIdentity when you create it.

For reference:
https://stackoverflow.com/questions/20254796/why-is-my-claimsidentity-isauthenticated-always-false-for-web-api-authorize-fil

**Comment by aseminjakiw** [comment]
Is PR #4 present in latest package on NuGet? NuGet version 1.0.9 2020-05-04. I have decompiled it the package and the authentication type in ClaimsIdentity constructor is missing. Is it possible to update the NuGet package?

**Comment by dasiths** [comment]
The latest release should be `1.0.10`. I may have not published it. Let me double check.

**Comment by dasiths** [comment]
> Is PR #4 present in latest package on NuGet? NuGet version 1.0.9 2020-05-04. I have decompiled it the package and the authentication type in ClaimsIdentity constructor is missing. Is it possible to update the NuGet package?

I've just pushed 1.0.10 out now.

**Comment by aseminjakiw** [comment]
> 
> 
> > Is PR #4 present in latest package on NuGet? NuGet version 1.0.9 2020-05-04. I have decompiled it the package and the authentication type in ClaimsIdentity constructor is missing. Is it possible to update the NuGet package?
> 
> I've just pushed 1.0.10 out now.

Thank you so much. Now it runs like a charm. :-)
