### ISSUE TITLE
NEasyAuthMiddleware 2.0.0 is not compatible with net50-windows7.0 

### ISSUE THREAD

**Issue by muhammadyehia** [dasiths/NEasyAuthMiddleware#9]
##[error]The nuget command failed with exit code(1) and error(NU1202: Package NEasyAuthMiddleware 2.0.0 is not compatible with net50-windows7.0 (.NETFramework,Version=v5.0,Profile=windows7.0). Package NEasyAuthMiddleware 2.0.0 supports: netcoreapp3.0 (.NETCoreApp,Version=v3.0)

**Comment by dasiths** [comment]
This has been updated to support .NET 8 now. https://www.nuget.org/packages/NEasyAuthMiddleware/3.0.9
